version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      target: prod # Use the production Nginx stage
    ports:
      - "80:80" # Expose on standard HTTP port
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: prod # Use production Node.js stage
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
