const he = {
    isAuthenticated: [Function: isAuthenticated],
    isUnauthenticated: [Function: isUnauthenticated],
    getUser: [Function: getUser],
    authenticate: [Function: authenticate],
    login: [Function: login],
    logout: [Function: logout],
    req: <ref * 1 > IncomingMessage {
        _events: {
            close: undefined,
            error: undefined,
            data: undefined,
            end: undefined,
            readable: undefined,
            aborted: undefined
        },
        _readableState: ReadableState {
            highWaterMark: 65536,
            buffer: [],
            bufferIndex: 0,
            length: 0,
            pipes: [],
            awaitDrainWriters: null,
            [Symbol(kState)]: 60295036
        },
    _maxListeners: undefined,
    socket: Socket {
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _closeAfterHandlingError: false,
        _events: [Object],
        _readableState: [ReadableState],
        _writableState: [WritableState],
        allowHalfOpen: true,
        _maxListeners: undefined,
        _eventsCount: 8,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Server],
        _server: [Server],
        parser: [HTTPParser],
        on: [Function: socketListenerWrap],
        addListener: [Function: socketListenerWrap],
        prependListener: [Function: socketListenerWrap],
        setEncoding: [Function: socketSetEncoding],
        _paused: false,
        _httpMessage: [ServerResponse],
        [Symbol(async_id_symbol)]: 3947,
        [Symbol(kHandle)]: [TCP],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(shapeMode)]: true,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: true,
        [Symbol(kSetKeepAlive)]: false,
        [Symbol(kSetKeepAliveInitialDelay)]: 0,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
        },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    rawHeaders: [
        'Host',
        'localhost:4000',
        'Connection',
        'keep-alive',
        'Content-Length',
        '299',
        'sec-ch-ua-platform',
        '"macOS"',
        'User-Agent',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
        'accept',
        '*/*',
        'sec-ch-ua',
        '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
        'content-type',
        'application/json',
        'sec-ch-ua-mobile',
        '?0',
        'Origin',
        'http://localhost:5173',
        'Sec-Fetch-Site',
        'same-site',
        'Sec-Fetch-Mode',
        'cors',
        'Sec-Fetch-Dest',
        'empty',
        'Referer',
        'http://localhost:5173/',
        'Accept-Encoding',
        'gzip, deflate, br, zstd',
        'Accept-Language',
        'en-US,en;q=0.9',
        'Cookie',
        'next-auth.csrf-token=d806da132278815fd08d06ffb9d3b5c7b5415a03e4adaac4396aaf58f8e8929f%7C77896b9cd1da2ee0fc04b3d62a195afdfab66eb64c5b78e635e0752a5636c34c; next-auth.callback-url=http%3A%2F%2Flocalhost%3A3000%2Fsign-in'
    ],
    rawTrailers: [],
    joinDuplicateHeaders: null,
    aborted: false,
    upgrade: false,
    url: '/',
    method: 'POST',
    statusCode: null,
    statusMessage: null,
    client: Socket {
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: null,
        _closeAfterHandlingError: false,
        _events: [Object],
        _readableState: [ReadableState],
        _writableState: [WritableState],
        allowHalfOpen: true,
        _maxListeners: undefined,
        _eventsCount: 8,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Server],
        _server: [Server],
        parser: [HTTPParser],
        on: [Function: socketListenerWrap],
        addListener: [Function: socketListenerWrap],
        prependListener: [Function: socketListenerWrap],
        setEncoding: [Function: socketSetEncoding],
        _paused: false,
        _httpMessage: [ServerResponse],
        [Symbol(async_id_symbol)]: 3947,
        [Symbol(kHandle)]: [TCP],
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(shapeMode)]: true,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: true,
        [Symbol(kSetKeepAlive)]: false,
        [Symbol(kSetKeepAliveInitialDelay)]: 0,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
        },
    _consuming: true,
    _dumped: false,
    next: [Function: next],
    baseUrl: '/graphql',
    originalUrl: '/graphql',
    _parsedUrl: Url {
        protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: null,
        query: null,
        pathname: '/graphql',
        path: '/graphql',
        href: '/graphql',
        _raw: '/graphql'
        },
    params: {},
    query: {},
    res: ServerResponse {
        _events: [Object: null prototype],
        _eventsCount: 1,
        _maxListeners: undefined,
        outputData: [],
        outputSize: 0,
        writable: true,
        destroyed: false,
        _last: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        maxRequestsOnConnectionReached: false,
        _defaultKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        strictContentLength: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: false,
        _closed: false,
        _header: null,
        _keepAliveTimeout: 5000,
        _onPendingData: [Function: bound updateOutgoingData],
        req: [Circular * 1],
_sent100: false,
    _expect_continue: false,
        _maxRequestsPerSocket: 0,
            locals: [Object: null prototype] { },
writeHead: [Function: writeHead],
    end: [Function: end],
        [Symbol(shapeMode)]: false,
            [Symbol(kCapture)]: false,
                [Symbol(kBytesWritten)]: 0,
                    [Symbol(kNeedDrain)]: false,
                        [Symbol(corked)]: 0,
                            [Symbol(kChunkedBuffer)]: [],
                                [Symbol(kChunkedLength)]: 0,
                                    [Symbol(kSocket)]: [Socket],
                                        [Symbol(kOutHeaders)]: [Object: null prototype],
                                            [Symbol(errored)]: null,
                                                [Symbol(kHighWaterMark)]: 65536,
                                                    [Symbol(kRejectNonStandardBodyWrites)]: false,
                                                        [Symbol(kUniqueHeaders)]: null
        },
body: {
    operationName: 'SignupUser',
        variables: [Object],
            query: 'mutation SignupUser($input: SignUpInput!) {\n' +
                '  signup(input: $input) {\n' +
                '    _id\n' +
                '    username\n' +
                '    name\n' +
                '    gender\n' +
                '    profilePicture\n' +
                '    __typename\n' +
                '  }\n' +
                '}'
},
_body: true,
    length: undefined,
        _eventsCount: 0,
            _parsedOriginalUrl: Url {
    protocol: null,
        slashes: null,
            auth: null,
                host: null,
                    port: null,
                        hostname: null,
                            hash: null,
                                search: null,
                                    query: null,
                                        pathname: '/graphql',
                                            path: '/graphql',
                                                href: '/graphql',
                                                    _raw: '/graphql'
},
sessionStore: Store {
    _emitter: [EventEmitter],
        _errorHandler: [Function: bound handleError],
            client: [MongoClient],
                db: [Db],
                    _events: [Object: null prototype] { },
    _eventsCount: 0,
        _maxListeners: undefined,
            options: [OptionsType],
                collection: [Collection],
                    initialConnectionPromise: [Promise],
                        generate: [Function(anonymous)],
                            [Symbol(shapeMode)]: false,
                                [Symbol(kCapture)]: false
},
sessionID: 'aVy4IVGzTBOhDP4R0FZgV0J72K_anoWj',
    session: Session { cookie: [Object] },
logIn: [Function(anonymous)],
    login: [Function(anonymous)],
        logOut: [Function(anonymous)],
            logout: [Function(anonymous)],
                isAuthenticated: [Function(anonymous)],
                    isUnauthenticated: [Function(anonymous)],
                        _sessionManager: SessionManager {
    _key: 'passport',
        _serializeUser: [Function: bound]
},
_passport: { instance: [Authenticator] },
[Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false,
        [Symbol(kHeaders)]: {
    host: 'localhost:4000',
        connection: 'keep-alive',
            'content-length': '299',
                'sec-ch-ua-platform': '"macOS"',
                    'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36',
                        accept: '*/*',
                            'sec-ch-ua': '"Chromium";v="130", "Google Chrome";v="130", "Not?A_Brand";v="99"',
                                'content-type': 'application/json',
                                    'sec-ch-ua-mobile': '?0',
                                        origin: 'http://localhost:5173',
                                            'sec-fetch-site': 'same-site',
                                                'sec-fetch-mode': 'cors',
                                                    'sec-fetch-dest': 'empty',
                                                        referer: 'http://localhost:5173/',
                                                            'accept-encoding': 'gzip, deflate, br, zstd',
                                                                'accept-language': 'en-US,en;q=0.9',
                                                                    cookie: 'next-auth.csrf-token=d806da132278815fd08d06ffb9d3b5c7b5415a03e4adaac4396aaf58f8e8929f%7C77896b9cd1da2ee0fc04b3d62a195afdfab66eb64c5b78e635e0752a5636c34c; next-auth.callback-url=http%3A%2F%2Flocalhost%3A3000%2Fsign-in'
},
[Symbol(kHeadersCount)]: 34,
    [Symbol(kTrailers)]: null,
        [Symbol(kTrailersCount)]: 0
    },
res: <ref * 2 > ServerResponse {
    _events: [Object: null prototype] { finish: [Array] },
    _eventsCount: 1,
        _maxListeners: undefined,
            outputData: [],
                outputSize: 0,
                    writable: true,
                        destroyed: false,
                            _last: false,
                                chunkedEncoding: false,
                                    shouldKeepAlive: true,
                                        maxRequestsOnConnectionReached: false,
                                            _defaultKeepAlive: true,
                                                useChunkedEncodingByDefault: true,
                                                    sendDate: true,
                                                        _removedConnection: false,
                                                            _removedContLen: false,
                                                                _removedTE: false,
                                                                    strictContentLength: false,
                                                                        _contentLength: null,
                                                                            _hasBody: true,
                                                                                _trailer: '',
                                                                                    finished: false,
                                                                                        _headerSent: false,
                                                                                            _closed: false,
                                                                                                _header: null,
                                                                                                    _keepAliveTimeout: 5000,
                                                                                                        _onPendingData: [Function: bound updateOutgoingData],
                                                                                                            req: <ref * 1 > IncomingMessage {
        _events: [Object],
            _readableState: [ReadableState],
                _maxListeners: undefined,
                    socket: [Socket],
                        httpVersionMajor: 1,
                            httpVersionMinor: 1,
                                httpVersion: '1.1',
                                    complete: true,
                                        rawHeaders: [Array],
                                            rawTrailers: [],
                                                joinDuplicateHeaders: null,
                                                    aborted: false,
                                                        upgrade: false,
                                                            url: '/',
                                                                method: 'POST',
                                                                    statusCode: null,
                                                                        statusMessage: null,
                                                                            client: [Socket],
                                                                                _consuming: true,
                                                                                    _dumped: false,
                                                                                        next: [Function: next],
                                                                                            baseUrl: '/graphql',
                                                                                                originalUrl: '/graphql',
                                                                                                    _parsedUrl: [Url],
                                                                                                        params: { },
        query: { },
        res: [Circular * 2],
            body: [Object],
                _body: true,
                    length: undefined,
                        _eventsCount: 0,
                            _parsedOriginalUrl: [Url],
                                sessionStore: [Store],
                                    sessionID: 'aVy4IVGzTBOhDP4R0FZgV0J72K_anoWj',
                                        session: [Session],
                                            logIn: [Function(anonymous)],
                                                login: [Function(anonymous)],
                                                    logOut: [Function(anonymous)],
                                                        logout: [Function(anonymous)],
                                                            isAuthenticated: [Function(anonymous)],
                                                                isUnauthenticated: [Function(anonymous)],
                                                                    _sessionManager: [SessionManager],
                                                                        _passport: [Object],
                                                                            [Symbol(shapeMode)]: true,
                                                                                [Symbol(kCapture)]: false,
                                                                                    [Symbol(kHeaders)]: [Object],
                                                                                        [Symbol(kHeadersCount)]: 34,
                                                                                            [Symbol(kTrailers)]: null,
                                                                                                [Symbol(kTrailersCount)]: 0
    },
    _sent100: false,
        _expect_continue: false,
            _maxRequestsPerSocket: 0,
                locals: [Object: null prototype] { },
    writeHead: [Function: writeHead],
        end: [Function: end],
            [Symbol(shapeMode)]: false,
                [Symbol(kCapture)]: false,
                    [Symbol(kBytesWritten)]: 0,
                        [Symbol(kNeedDrain)]: false,
                            [Symbol(corked)]: 0,
                                [Symbol(kChunkedBuffer)]: [],
                                    [Symbol(kChunkedLength)]: 0,
                                        [Symbol(kSocket)]: Socket {
        connecting: false,
            _hadError: false,
                _parent: null,
                    _host: null,
                        _closeAfterHandlingError: false,
                            _events: [Object],
                                _readableState: [ReadableState],
                                    _writableState: [WritableState],
                                        allowHalfOpen: true,
                                            _maxListeners: undefined,
                                                _eventsCount: 8,
                                                    _sockname: null,
                                                        _pendingData: null,
                                                            _pendingEncoding: '',
                                                                server: [Server],
                                                                    _server: [Server],
                                                                        parser: [HTTPParser],
                                                                            on: [Function: socketListenerWrap],
                                                                                addListener: [Function: socketListenerWrap],
                                                                                    prependListener: [Function: socketListenerWrap],
                                                                                        setEncoding: [Function: socketSetEncoding],
                                                                                            _paused: false,
                                                                                                _httpMessage: [Circular * 2],
                                                                                                    [Symbol(async_id_symbol)]: 3947,
                                                                                                        [Symbol(kHandle)]: [TCP],
                                                                                                            [Symbol(lastWriteQueueSize)]: 0,
                                                                                                                [Symbol(timeout)]: null,
                                                                                                                    [Symbol(kBuffer)]: null,
                                                                                                                        [Symbol(kBufferCb)]: null,
                                                                                                                            [Symbol(kBufferGen)]: null,
                                                                                                                                [Symbol(shapeMode)]: true,
                                                                                                                                    [Symbol(kCapture)]: false,
                                                                                                                                        [Symbol(kSetNoDelay)]: true,
                                                                                                                                            [Symbol(kSetKeepAlive)]: false,
                                                                                                                                                [Symbol(kSetKeepAliveInitialDelay)]: 0,
                                                                                                                                                    [Symbol(kBytesRead)]: 0,
                                                                                                                                                        [Symbol(kBytesWritten)]: 0
    },
    [Symbol(kOutHeaders)]: [Object: null prototype] {
        'x-powered-by': [Array],
            'access-control-allow-origin': [Array],
                vary: [Array],
                    'access-control-allow-credentials': [Array]
    },
    [Symbol(errored)]: null,
        [Symbol(kHighWaterMark)]: 65536,
            [Symbol(kRejectNonStandardBodyWrites)]: false,
                [Symbol(kUniqueHeaders)]: null
}
}